sudo: required
dist: trusty
group: deprecated-2017Q4

language: python
notification:
    email: false

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - pushd .
  - sudo apt-get update -qq
  - sudo apt-get install -y curl erlang python-dev
  - git clone https://github.com/discoproject/disco.git /tmp/disco
  - cd /tmp/disco && git checkout develop && sudo make install
  - cd lib && pip install .
  - popd

install:
  - sudo bash ./bootstrap.sh
  - sudo pip install -r requirements-dev.txt

script: nosetests test/
